api = "0.2"

[buildpack]
  id = "com.example.drupal-scaffold-2"
  name = "Drupal scaffold 2"
  version = "0.0.1"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"


[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[metadata]
  [[metadata.dependencies]]
    uri = "https://nodejs.org/dist/v12.16.1/node-v12.16.1-linux-x64.tar.xz"
